repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Check whether files parse as valid python.
      - id: check-ast
        types: [python]
      # Attempts to load all json files to verify syntax.
      - id: check-json
        types: [json]
      # Attempts to load all TOML files to verify syntax.
      - id: check-toml
        types: [toml]
      # Attempts to load all xml files to verify syntax.
      - id: check-xml
        types: [xml]
      # Attempts to load all yaml files to verify syntax.
      - id: check-yaml
        types: [yaml]
        exclude: "^helm/|.github/"
      # Makes sure files end in a newline and only a newline.
      - id: end-of-file-fixer
      # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
      - id: check-case-conflict
      # Checks for files that contain merge conflict strings like `<<<<<<< HEAD`.
      - id: check-merge-conflict
      # Checks that all your JSON files are pretty. "Pretty" here means that keys are sorted and indented.
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
          - --no-ensure-ascii
      # Trims trailing whitespace.
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      # Prevent giant files from being committed.
      - id: check-added-large-files

  # Ruff - An extremely fast Python linter and code formatter, written in Rust.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff

  # Pyright - Static type checker for Python
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: bash -c 'pyright'
        language: system
        types: [python]
        pass_filenames: false
