from python_utils.entity import Entity as Entity
from python_utils.testing.directory import set_working_directory as set_working_directory
from python_utils.testing.docker import start_service as start_service, stop_service as stop_service
from sqlalchemy.engine.base import Engine as Engine

def wait_for_db_to_be_ready(db_name: str, user: str, password: str, host: str, port: int, max_attempts: int = 20) -> None: ...
def run_alembic_migrations(work_dir: str) -> None: ...
def reset_sqlalchemy_model_table(engine: Engine, entity: type[Entity]) -> None: ...
def database_container(docker_compose_psql_dir: str, service_name: str, db_name: str, user: str, password: str, host: str, port: int): ...
