from python_utils.testing.directory import set_working_directory as set_working_directory

def start_service(service_name: str, workdir: str) -> None: ...
def stop_service(service_name: str, workdir: str) -> None: ...
def docker_compose_dir(docker_compose_file_content: str): ...
