import subprocess
from typing import Any

def run_in_subprocess(command: str, env: dict[str, Any] = {}) -> subprocess.Popen[bytes]: ...
def run_web_server(server_file_path: str, max_check_health_attempts: int = 10): ...
def get_next_available_port() -> int: ...
def wait_for_server_to_be_ready(url: str, max_attempts: int): ...
