name: 🧩 Manage release

on:
  workflow_call:
    inputs:
      package-name:
        description: "Name of the published package"
        type: string
        required: true
      extra-version-files:
        description: "list of extra files in which update the version"
        type: string
        required: false
        default: "[]"
      release-type:
        description: "Type of release"
        type: string
        required: false
        default: "python"
permissions:
  contents: write
  pull-requests: write

jobs:
  manage_release:
    name: Manage release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: ${{ inputs.release-type }}
          package-name: ${{ inputs.package-name }}
          token: ${{ github.token }}
          extra-files: ${{ inputs.extra-version-files }}
