name: On commit on main branch

on:
  push:
    branches:
      - main

jobs:
  check-python-code:
    name: Check python code
    uses: ./.github/workflows/callable__check_python_code.yml
    secrets: inherit
    with:
      pytest-root: "."

  manage_release:
    needs: check-python-code
    name: Manage release
    uses: ./.github/workflows/callable__manage_release.yml
    secrets: inherit
    with:
      package-name: "python_utils"
