name: On commit on main branch

on:
  push:
    branches:
      - main

jobs:
  check-python-code:
    name: Check python code
    uses: ./.github/workflows/callable__check_python_code.yaml
    secrets: inherit
    with:
      pytest-root: "."

  build-and-release:
    name: Build and release
    uses: ./.github/workflows/callable__build_and_release.yaml
    needs: check-python-code
    secrets: inherit
    with:
      package-name: "python_utils"
